training/account/urls.py
from django.conf.urls import url
from .views import dashboard, signup_view, login_view, logout_view

app_name = 'account'

urlpatterns = [
    url(r'^signup/$', signup_view, name='signup'),
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r"^dashboard", dashboard, name="dashboard")
]

training/train/urls.py
from django.conf.urls import url
from . import views

app_name = 'train'

urlpatterns = [
    url(r'^$', views.index_view, name='index'),
    url(r'^addrequest/$', views.add_request, name='add_request'),

]

training/training/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('account/', include("account.urls")),
    path('train/', include("train.urls")),
    path('admin/', admin.site.urls),

]

training/train/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
#from training.settings import EMAIL_HOST_USER


# Create your models here.
class RegisterRequest(models.Model):
    REQUEST_STATUS = (
        ('waiting', _('waiting')),
        ('approved', _('approved')),
        ('rejected', _('rejected')),
    )
    name = models.CharField(max_length=200)
    email = models.EmailField()
    status = models.CharField(verbose_name=_('Request status'),
                              max_length=200,
                              default='waiting',
                              choices=REQUEST_STATUS)

    class Meta:
        verbose_name = _('Register request ')
        verbose_name_plural = _('Register requests ')

training/train/forms.py
from django.forms import ModelForm
from .models import RegisterRequest


class RequestRegisterForm(ModelForm):
    class Meta:
        model = RegisterRequest
        exclude = ['status']

training/train/views.py
from django.shortcuts import render, redirect
from .forms import RequestRegisterForm
from handle.models import RegisterRequestState
from .models import RegisterRequest


# Create your views here.

def index_view(request):
    return render(request, "train/base.html")


def add_request(request):
    if request.method == 'POST':
        form = RequestRegisterForm(request.POST)

        if form.is_valid():
            register_request = form.save()
            request_state = RegisterRequestState.objects.create(
                register_request=register_request,
                flag='pending_employee_review'
            )

            return redirect('train:index')
    else:
        form = RequestRegisterForm()
    return render(request, 'train/add_request.html', {'form': form})

training/train/templates/train/add_request.html
{% extends "train/base.html" %}

{% block content %}

    <h4> add your request </h4>

    <form action="{% url 'train:add_request' %}" method="post" >
        {% csrf_token %}
        {{form}}
        <input type="submit" value="add_request">
    </form>

{% endblock %}

training/train/templates/train/base.html
{% load static i18n %}

<html>

<head>

    <link rel="stylesheet" href="https://bootswatch.com/4/superhero/bootstrap.min.css">

</head>

{% block navbar %}
{% include "train/navigation.html" %}
{% endblock %}

{% block content %}
{% block content-main %}
{% endblock %}
{% endblock %}

</html>

training/train/templates/train/navigation.html
{% load static i18n %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Training</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
          aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <div id="topbar">

        <div class="navbar">

             <div class="navbar-content">

                <div class="navbar-nav mr-auto">

                     <a class="navbar" href="">
                         <b>Training</b></a>

                     <a class="navbar" href="{% url 'train:add_request' %}">
                         add Request </a>

                     <a class="navbar" href="{% url 'account:login' %}">
                        Login </a>

                     <a class="navbar" href="{% url 'account:signup' %}">
                         Signup </a>

                     <a class="navbar" href=" {% url 'account:logout' %}">
                         Logout </a>

                    <br>
                </div>

             </div>

        </div>

      </div>

    </div>
</nav>